/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace InvoiceNFT {
      
    export type CreditProfileStruct = {score: BigNumberish, totalInvoices: BigNumberish, successfulSettlements: BigNumberish, lateSettlements: BigNumberish, defaults: BigNumberish, lastUpdated: BigNumberish, totalSettlementHours: BigNumberish, totalFundingReceived: BigNumberish, totalFundingProvided: BigNumberish, approvedInvoices: BigNumberish, fundedInvoices: BigNumberish, settledInvoices: BigNumberish, activeInvestments: BigNumberish, completedInvestments: BigNumberish, totalCapitalInvested: BigNumberish, totalInvestedInCompleted: BigNumberish, totalCapitalRecovered: BigNumberish}

    export type CreditProfileStructOutput = [score: bigint, totalInvoices: bigint, successfulSettlements: bigint, lateSettlements: bigint, defaults: bigint, lastUpdated: bigint, totalSettlementHours: bigint, totalFundingReceived: bigint, totalFundingProvided: bigint, approvedInvoices: bigint, fundedInvoices: bigint, settledInvoices: bigint, activeInvestments: bigint, completedInvestments: bigint, totalCapitalInvested: bigint, totalInvestedInCompleted: bigint, totalCapitalRecovered: bigint] & {score: bigint, totalInvoices: bigint, successfulSettlements: bigint, lateSettlements: bigint, defaults: bigint, lastUpdated: bigint, totalSettlementHours: bigint, totalFundingReceived: bigint, totalFundingProvided: bigint, approvedInvoices: bigint, fundedInvoices: bigint, settledInvoices: bigint, activeInvestments: bigint, completedInvestments: bigint, totalCapitalInvested: bigint, totalInvestedInCompleted: bigint, totalCapitalRecovered: bigint }
  
    }

  export interface InvoiceNFTInterface extends Interface {
    getFunction(nameOrSignature: "BAD_RATIO" | "CREDIT_WEIGHT" | "DEFAULT_PENALTY" | "DEFAULT_WEIGHT" | "FINANCIER_REWARD" | "GOOD_RATIO" | "HISTORY_BONUS" | "HISTORY_PENALTY" | "HISTORY_THRESHOLD" | "INITIAL_SCORE" | "InvoiceNFT_Map" | "LATE_PENALTY" | "MAX_DISCOUNT" | "MIN_DISCOUNT" | "ONTIME_REWARD" | "REPAYMENT_REWARD" | "SCORE_MAX" | "SETTLEMENT_WEIGHT" | "SIGN_REWARD" | "SUPPLIER_REWARD" | "URGENCY_NEAR_30D" | "URGENCY_NEAR_7D" | "URGENCY_PAST_DUE" | "approve" | "approveInvoiceSale" | "approveInvoiceSaleWithRecommendation" | "balanceOf" | "buyInvoice" | "calculateRiskScore" | "cidUsed" | "creditProfiles" | "discountRecommendations" | "getApproved" | "getBuyerBBCS" | "getBuyerBBCSBreakdown" | "getCreditProfile" | "getCreditScore" | "getResearchMetrics" | "invoiceDefaulted" | "invoiceDueDateTimestamp" | "invoiceInvestmentAmount" | "invoiceMintedAt" | "invoiceSettledFlag" | "isApprovedForAll" | "markDefault" | "mintInvoice" | "name" | "ownerOf" | "recommendDiscount" | "revokeInvoiceSale" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "setInvoiceDueTimestamp" | "settleInvoice" | "signInvoice" | "supportsInterface" | "symbol" | "tokenURI" | "transferFrom"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "BatchMetadataUpdate" | "CreditScoreUpdated" | "InvoiceBought" | "InvoiceDefaultedEvent" | "InvoiceListedForSale" | "InvoiceMinted" | "InvoiceSaleRevoked" | "InvoiceSettled" | "InvoiceSigned" | "MetadataUpdate" | "RecommendationGenerated" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'BAD_RATIO', values?: undefined): string;
encodeFunctionData(functionFragment: 'CREDIT_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_PENALTY', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'FINANCIER_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'GOOD_RATIO', values?: undefined): string;
encodeFunctionData(functionFragment: 'HISTORY_BONUS', values?: undefined): string;
encodeFunctionData(functionFragment: 'HISTORY_PENALTY', values?: undefined): string;
encodeFunctionData(functionFragment: 'HISTORY_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'INITIAL_SCORE', values?: undefined): string;
encodeFunctionData(functionFragment: 'InvoiceNFT_Map', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'LATE_PENALTY', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_DISCOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DISCOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'ONTIME_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'REPAYMENT_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'SCORE_MAX', values?: undefined): string;
encodeFunctionData(functionFragment: 'SETTLEMENT_WEIGHT', values?: undefined): string;
encodeFunctionData(functionFragment: 'SIGN_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'SUPPLIER_REWARD', values?: undefined): string;
encodeFunctionData(functionFragment: 'URGENCY_NEAR_30D', values?: undefined): string;
encodeFunctionData(functionFragment: 'URGENCY_NEAR_7D', values?: undefined): string;
encodeFunctionData(functionFragment: 'URGENCY_PAST_DUE', values?: undefined): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveInvoiceSale', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveInvoiceSaleWithRecommendation', values: [BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buyInvoice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateRiskScore', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cidUsed', values: [string]): string;
encodeFunctionData(functionFragment: 'creditProfiles', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'discountRecommendations', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBuyerBBCS', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getBuyerBBCSBreakdown', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCreditProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCreditScore', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getResearchMetrics', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'invoiceDefaulted', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'invoiceDueDateTimestamp', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'invoiceInvestmentAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'invoiceMintedAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'invoiceSettledFlag', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'markDefault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintInvoice', values: [string, AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recommendDiscount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeInvoiceSale', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setInvoiceDueTimestamp', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settleInvoice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'signInvoice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'BAD_RATIO', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'CREDIT_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_PENALTY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FINANCIER_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'GOOD_RATIO', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HISTORY_BONUS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HISTORY_PENALTY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'HISTORY_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'INITIAL_SCORE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'InvoiceNFT_Map', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LATE_PENALTY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_DISCOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DISCOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ONTIME_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REPAYMENT_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SCORE_MAX', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SETTLEMENT_WEIGHT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SIGN_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SUPPLIER_REWARD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'URGENCY_NEAR_30D', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'URGENCY_NEAR_7D', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'URGENCY_PAST_DUE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveInvoiceSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveInvoiceSaleWithRecommendation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateRiskScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cidUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creditProfiles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'discountRecommendations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuyerBBCS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuyerBBCSBreakdown', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreditProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreditScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getResearchMetrics', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invoiceDefaulted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invoiceDueDateTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invoiceInvestmentAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invoiceMintedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invoiceSettledFlag', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markDefault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recommendDiscount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeInvoiceSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setInvoiceDueTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchMetadataUpdateEvent {
      export type InputTuple = [_fromTokenId: BigNumberish, _toTokenId: BigNumberish];
      export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
      export interface OutputObject {_fromTokenId: bigint, _toTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CreditScoreUpdatedEvent {
      export type InputTuple = [participant: AddressLike, oldScore: BigNumberish, newScore: BigNumberish, reason: string];
      export type OutputTuple = [participant: string, oldScore: bigint, newScore: bigint, reason: string];
      export interface OutputObject {participant: string, oldScore: bigint, newScore: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceBoughtEvent {
      export type InputTuple = [tokenId: BigNumberish, previousOwner: AddressLike, newOwner: AddressLike, price: BigNumberish];
      export type OutputTuple = [tokenId: bigint, previousOwner: string, newOwner: string, price: bigint];
      export interface OutputObject {tokenId: bigint, previousOwner: string, newOwner: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceDefaultedEventEvent {
      export type InputTuple = [tokenId: BigNumberish, buyer: AddressLike];
      export type OutputTuple = [tokenId: bigint, buyer: string];
      export interface OutputObject {tokenId: bigint, buyer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceListedForSaleEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike, price: BigNumberish];
      export type OutputTuple = [tokenId: bigint, owner: string, price: bigint];
      export interface OutputObject {tokenId: bigint, owner: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceMintedEvent {
      export type InputTuple = [tokenId: BigNumberish, creator: AddressLike, buyer: AddressLike, invoiceAmount: BigNumberish, dueDate: string];
      export type OutputTuple = [tokenId: bigint, creator: string, buyer: string, invoiceAmount: bigint, dueDate: string];
      export interface OutputObject {tokenId: bigint, creator: string, buyer: string, invoiceAmount: bigint, dueDate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceSaleRevokedEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [tokenId: bigint, owner: string];
      export interface OutputObject {tokenId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceSettledEvent {
      export type InputTuple = [tokenId: BigNumberish, previousOwner: AddressLike, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tokenId: bigint, previousOwner: string, buyer: string, amount: bigint];
      export interface OutputObject {tokenId: bigint, previousOwner: string, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceSignedEvent {
      export type InputTuple = [tokenId: BigNumberish, buyer: AddressLike];
      export type OutputTuple = [tokenId: bigint, buyer: string];
      export interface OutputObject {tokenId: bigint, buyer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataUpdateEvent {
      export type InputTuple = [_tokenId: BigNumberish];
      export type OutputTuple = [_tokenId: bigint];
      export interface OutputObject {_tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecommendationGeneratedEvent {
      export type InputTuple = [tokenId: BigNumberish, riskScore: BigNumberish, recommendedDiscount: BigNumberish, finalDiscount: BigNumberish];
      export type OutputTuple = [tokenId: bigint, riskScore: bigint, recommendedDiscount: bigint, finalDiscount: bigint];
      export interface OutputObject {tokenId: bigint, riskScore: bigint, recommendedDiscount: bigint, finalDiscount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InvoiceNFT extends BaseContract {
    
    connect(runner?: ContractRunner | null): InvoiceNFT;
    waitForDeployment(): Promise<this>;

    interface: InvoiceNFTInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BAD_RATIO: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    CREDIT_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_PENALTY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FINANCIER_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    GOOD_RATIO: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    HISTORY_BONUS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    HISTORY_PENALTY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    HISTORY_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    INITIAL_SCORE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    InvoiceNFT_Map: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, string, boolean, boolean] & {creator: string, buyer: string, currPrice: bigint, invoiceAmount: bigint, dueDate: string, isApproved: boolean, forSale: boolean }],
      'view'
    >
    

    
    LATE_PENALTY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_DISCOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DISCOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ONTIME_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    REPAYMENT_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SCORE_MAX: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SETTLEMENT_WEIGHT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SIGN_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SUPPLIER_REWARD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    URGENCY_NEAR_30D: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    URGENCY_NEAR_7D: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    URGENCY_PAST_DUE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approveInvoiceSale: TypedContractMethod<
      [_tokenId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approveInvoiceSaleWithRecommendation: TypedContractMethod<
      [_tokenId: BigNumberish, _price: BigNumberish, _useRecommended: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    buyInvoice: TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    calculateRiskScore: TypedContractMethod<
      [buyer: AddressLike, tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cidUsed: TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >
    

    
    creditProfiles: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {score: bigint, totalInvoices: bigint, successfulSettlements: bigint, lateSettlements: bigint, defaults: bigint, lastUpdated: bigint, totalSettlementHours: bigint, totalFundingReceived: bigint, totalFundingProvided: bigint, approvedInvoices: bigint, fundedInvoices: bigint, settledInvoices: bigint, activeInvestments: bigint, completedInvestments: bigint, totalCapitalInvested: bigint, totalInvestedInCompleted: bigint, totalCapitalRecovered: bigint }],
      'view'
    >
    

    
    discountRecommendations: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {riskScore: bigint, recommendedDiscount: bigint, finalDiscount: bigint, supplierOverrode: boolean }],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getBuyerBBCS: TypedContractMethod<
      [buyer: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getBuyerBBCSBreakdown: TypedContractMethod<
      [buyer: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {settlementScore: bigint, defaultScore: bigint, experienceScore: bigint, finalBBCS: bigint }],
      'view'
    >
    

    
    getCreditProfile: TypedContractMethod<
      [participant: AddressLike, ],
      [InvoiceNFT.CreditProfileStructOutput],
      'view'
    >
    

    
    getCreditScore: TypedContractMethod<
      [participant: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getResearchMetrics: TypedContractMethod<
      [participant: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {score: bigint, settlementRatio: bigint, defaultRatio: bigint, avgSettlementHours: bigint, totalFundingRcvd: bigint, totalFundingPrvd: bigint }],
      'view'
    >
    

    
    invoiceDefaulted: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    invoiceDueDateTimestamp: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    invoiceInvestmentAmount: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    invoiceMintedAt: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    invoiceSettledFlag: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    markDefault: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mintInvoice: TypedContractMethod<
      [_cid: string, _buyer: AddressLike, _invoiceAmount: BigNumberish, _dueDate: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    recommendDiscount: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, bigint] & {riskScore: bigint, recommendedDiscount: bigint }],
      'view'
    >
    

    
    revokeInvoiceSale: TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setInvoiceDueTimestamp: TypedContractMethod<
      [tokenId: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settleInvoice: TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    signInvoice: TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BAD_RATIO'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'CREDIT_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_PENALTY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FINANCIER_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'GOOD_RATIO'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'HISTORY_BONUS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'HISTORY_PENALTY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'HISTORY_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'INITIAL_SCORE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'InvoiceNFT_Map'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, string, boolean, boolean] & {creator: string, buyer: string, currPrice: bigint, invoiceAmount: bigint, dueDate: string, isApproved: boolean, forSale: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'LATE_PENALTY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_DISCOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DISCOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ONTIME_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'REPAYMENT_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SCORE_MAX'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SETTLEMENT_WEIGHT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SIGN_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SUPPLIER_REWARD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'URGENCY_NEAR_30D'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'URGENCY_NEAR_7D'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'URGENCY_PAST_DUE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveInvoiceSale'): TypedContractMethod<
      [_tokenId: BigNumberish, _price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveInvoiceSaleWithRecommendation'): TypedContractMethod<
      [_tokenId: BigNumberish, _price: BigNumberish, _useRecommended: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyInvoice'): TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'calculateRiskScore'): TypedContractMethod<
      [buyer: AddressLike, tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cidUsed'): TypedContractMethod<
      [arg0: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'creditProfiles'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {score: bigint, totalInvoices: bigint, successfulSettlements: bigint, lateSettlements: bigint, defaults: bigint, lastUpdated: bigint, totalSettlementHours: bigint, totalFundingReceived: bigint, totalFundingProvided: bigint, approvedInvoices: bigint, fundedInvoices: bigint, settledInvoices: bigint, activeInvestments: bigint, completedInvestments: bigint, totalCapitalInvested: bigint, totalInvestedInCompleted: bigint, totalCapitalRecovered: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'discountRecommendations'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {riskScore: bigint, recommendedDiscount: bigint, finalDiscount: bigint, supplierOverrode: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBuyerBBCS'): TypedContractMethod<
      [buyer: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getBuyerBBCSBreakdown'): TypedContractMethod<
      [buyer: AddressLike, ],
      [[bigint, bigint, bigint, bigint] & {settlementScore: bigint, defaultScore: bigint, experienceScore: bigint, finalBBCS: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCreditProfile'): TypedContractMethod<
      [participant: AddressLike, ],
      [InvoiceNFT.CreditProfileStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCreditScore'): TypedContractMethod<
      [participant: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getResearchMetrics'): TypedContractMethod<
      [participant: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {score: bigint, settlementRatio: bigint, defaultRatio: bigint, avgSettlementHours: bigint, totalFundingRcvd: bigint, totalFundingPrvd: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'invoiceDefaulted'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'invoiceDueDateTimestamp'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'invoiceInvestmentAmount'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'invoiceMintedAt'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'invoiceSettledFlag'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markDefault'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintInvoice'): TypedContractMethod<
      [_cid: string, _buyer: AddressLike, _invoiceAmount: BigNumberish, _dueDate: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recommendDiscount'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, bigint] & {riskScore: bigint, recommendedDiscount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'revokeInvoiceSale'): TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setInvoiceDueTimestamp'): TypedContractMethod<
      [tokenId: BigNumberish, timestamp: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleInvoice'): TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'signInvoice'): TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BatchMetadataUpdate'): TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
getEvent(key: 'CreditScoreUpdated'): TypedContractEvent<CreditScoreUpdatedEvent.InputTuple, CreditScoreUpdatedEvent.OutputTuple, CreditScoreUpdatedEvent.OutputObject>;
getEvent(key: 'InvoiceBought'): TypedContractEvent<InvoiceBoughtEvent.InputTuple, InvoiceBoughtEvent.OutputTuple, InvoiceBoughtEvent.OutputObject>;
getEvent(key: 'InvoiceDefaultedEvent'): TypedContractEvent<InvoiceDefaultedEventEvent.InputTuple, InvoiceDefaultedEventEvent.OutputTuple, InvoiceDefaultedEventEvent.OutputObject>;
getEvent(key: 'InvoiceListedForSale'): TypedContractEvent<InvoiceListedForSaleEvent.InputTuple, InvoiceListedForSaleEvent.OutputTuple, InvoiceListedForSaleEvent.OutputObject>;
getEvent(key: 'InvoiceMinted'): TypedContractEvent<InvoiceMintedEvent.InputTuple, InvoiceMintedEvent.OutputTuple, InvoiceMintedEvent.OutputObject>;
getEvent(key: 'InvoiceSaleRevoked'): TypedContractEvent<InvoiceSaleRevokedEvent.InputTuple, InvoiceSaleRevokedEvent.OutputTuple, InvoiceSaleRevokedEvent.OutputObject>;
getEvent(key: 'InvoiceSettled'): TypedContractEvent<InvoiceSettledEvent.InputTuple, InvoiceSettledEvent.OutputTuple, InvoiceSettledEvent.OutputObject>;
getEvent(key: 'InvoiceSigned'): TypedContractEvent<InvoiceSignedEvent.InputTuple, InvoiceSignedEvent.OutputTuple, InvoiceSignedEvent.OutputObject>;
getEvent(key: 'MetadataUpdate'): TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
getEvent(key: 'RecommendationGenerated'): TypedContractEvent<RecommendationGeneratedEvent.InputTuple, RecommendationGeneratedEvent.OutputTuple, RecommendationGeneratedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BatchMetadataUpdate(uint256,uint256)': TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
      BatchMetadataUpdate: TypedContractEvent<BatchMetadataUpdateEvent.InputTuple, BatchMetadataUpdateEvent.OutputTuple, BatchMetadataUpdateEvent.OutputObject>;
    

      'CreditScoreUpdated(address,uint8,uint8,string)': TypedContractEvent<CreditScoreUpdatedEvent.InputTuple, CreditScoreUpdatedEvent.OutputTuple, CreditScoreUpdatedEvent.OutputObject>;
      CreditScoreUpdated: TypedContractEvent<CreditScoreUpdatedEvent.InputTuple, CreditScoreUpdatedEvent.OutputTuple, CreditScoreUpdatedEvent.OutputObject>;
    

      'InvoiceBought(uint256,address,address,uint256)': TypedContractEvent<InvoiceBoughtEvent.InputTuple, InvoiceBoughtEvent.OutputTuple, InvoiceBoughtEvent.OutputObject>;
      InvoiceBought: TypedContractEvent<InvoiceBoughtEvent.InputTuple, InvoiceBoughtEvent.OutputTuple, InvoiceBoughtEvent.OutputObject>;
    

      'InvoiceDefaultedEvent(uint256,address)': TypedContractEvent<InvoiceDefaultedEventEvent.InputTuple, InvoiceDefaultedEventEvent.OutputTuple, InvoiceDefaultedEventEvent.OutputObject>;
      InvoiceDefaultedEvent: TypedContractEvent<InvoiceDefaultedEventEvent.InputTuple, InvoiceDefaultedEventEvent.OutputTuple, InvoiceDefaultedEventEvent.OutputObject>;
    

      'InvoiceListedForSale(uint256,address,uint256)': TypedContractEvent<InvoiceListedForSaleEvent.InputTuple, InvoiceListedForSaleEvent.OutputTuple, InvoiceListedForSaleEvent.OutputObject>;
      InvoiceListedForSale: TypedContractEvent<InvoiceListedForSaleEvent.InputTuple, InvoiceListedForSaleEvent.OutputTuple, InvoiceListedForSaleEvent.OutputObject>;
    

      'InvoiceMinted(uint256,address,address,uint256,string)': TypedContractEvent<InvoiceMintedEvent.InputTuple, InvoiceMintedEvent.OutputTuple, InvoiceMintedEvent.OutputObject>;
      InvoiceMinted: TypedContractEvent<InvoiceMintedEvent.InputTuple, InvoiceMintedEvent.OutputTuple, InvoiceMintedEvent.OutputObject>;
    

      'InvoiceSaleRevoked(uint256,address)': TypedContractEvent<InvoiceSaleRevokedEvent.InputTuple, InvoiceSaleRevokedEvent.OutputTuple, InvoiceSaleRevokedEvent.OutputObject>;
      InvoiceSaleRevoked: TypedContractEvent<InvoiceSaleRevokedEvent.InputTuple, InvoiceSaleRevokedEvent.OutputTuple, InvoiceSaleRevokedEvent.OutputObject>;
    

      'InvoiceSettled(uint256,address,address,uint256)': TypedContractEvent<InvoiceSettledEvent.InputTuple, InvoiceSettledEvent.OutputTuple, InvoiceSettledEvent.OutputObject>;
      InvoiceSettled: TypedContractEvent<InvoiceSettledEvent.InputTuple, InvoiceSettledEvent.OutputTuple, InvoiceSettledEvent.OutputObject>;
    

      'InvoiceSigned(uint256,address)': TypedContractEvent<InvoiceSignedEvent.InputTuple, InvoiceSignedEvent.OutputTuple, InvoiceSignedEvent.OutputObject>;
      InvoiceSigned: TypedContractEvent<InvoiceSignedEvent.InputTuple, InvoiceSignedEvent.OutputTuple, InvoiceSignedEvent.OutputObject>;
    

      'MetadataUpdate(uint256)': TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
      MetadataUpdate: TypedContractEvent<MetadataUpdateEvent.InputTuple, MetadataUpdateEvent.OutputTuple, MetadataUpdateEvent.OutputObject>;
    

      'RecommendationGenerated(uint256,uint8,uint8,uint8)': TypedContractEvent<RecommendationGeneratedEvent.InputTuple, RecommendationGeneratedEvent.OutputTuple, RecommendationGeneratedEvent.OutputObject>;
      RecommendationGenerated: TypedContractEvent<RecommendationGeneratedEvent.InputTuple, RecommendationGeneratedEvent.OutputTuple, RecommendationGeneratedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }