// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// ─────────────────────────────────────────────────────────────────────────────
//  IZKVerifier — Interface for on-chain Groth16 proof verification.
//
//  InvoiceNFT communicates ONLY through this interface, keeping the verifier
//  contract upgradeable without touching the core business contract.
//
//  Implementing contract: Groth16Verifier.sol  (generated by snarkjs)
//
//  Circuit public inputs order (matches invoice.circom):
//    pubSignals[0] = invoiceId
//    pubSignals[1] = buyerAddress  (as field element / decimal)
//    pubSignals[2] = minimumThreshold
//    pubSignals[3] = commitment    (Poseidon hash)
// ─────────────────────────────────────────────────────────────────────────────

interface IZKVerifier {
    /**
     * @notice Verify a Groth16 proof.
     *
     * @param _pA          Proof element π_a  (G1 point)
     * @param _pB          Proof element π_b  (G2 point)
     * @param _pC          Proof element π_c  (G1 point)
     * @param _pubSignals  Array of 4 public signals:
     *                       [invoiceId, buyerAddress, minimumThreshold, commitment]
     *
     * @return bool  true  if the proof is valid
     *               false if the proof is invalid
     */
    function verifyProof(
        uint256[2]    calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2]    calldata _pC,
        uint256[4]    calldata _pubSignals
    ) external view returns (bool);
}
